/*
 * Copyright (c) 2019-2020 vanaur.
 *
 * This file is part of RCL
 * (see https://github.com/vanaur/The-Runtime-Core-Library).
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
/* C Abstract Syntax Implementation generated by the BNF Converter. */

#include <stdio.h>
#include <stdlib.h>
#include <VM\Core\Syntax\Absyn.h>


/********************   PVoid    ********************/
Program make_PVoid()
{
    Program tmp = (Program) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating PVoid!\n");
        exit(1);
    }
    tmp->kind = is_PVoid;
    return tmp;
}
/********************   Prog1    ********************/
Program make_Prog1(ListPreprocessor p1, ListDefinition p2, Operation p3)
{
    Program tmp = (Program) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Prog1!\n");
        exit(1);
    }
    tmp->kind = is_Prog1;
    tmp->u.prog1_.listpreprocessor_ = p1;
    tmp->u.prog1_.listdefinition_ = p2;
    tmp->u.prog1_.operation_ = p3;
    return tmp;
}
/********************   Prog2    ********************/
Program make_Prog2(ListPreprocessor p1, ListDefinition p2)
{
    Program tmp = (Program) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Prog2!\n");
        exit(1);
    }
    tmp->kind = is_Prog2;
    tmp->u.prog2_.listpreprocessor_ = p1;
    tmp->u.prog2_.listdefinition_ = p2;
    return tmp;
}
/********************   Prog3    ********************/
Program make_Prog3(ListPreprocessor p1, Operation p2)
{
    Program tmp = (Program) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Prog3!\n");
        exit(1);
    }
    tmp->kind = is_Prog3;
    tmp->u.prog3_.listpreprocessor_ = p1;
    tmp->u.prog3_.operation_ = p2;
    return tmp;
}
/********************   Prog4    ********************/
Program make_Prog4(ListDefinition p1, Operation p2)
{
    Program tmp = (Program) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Prog4!\n");
        exit(1);
    }
    tmp->kind = is_Prog4;
    tmp->u.prog4_.listdefinition_ = p1;
    tmp->u.prog4_.operation_ = p2;
    return tmp;
}
/********************   Prog5    ********************/
Program make_Prog5(ListDefinition p1)
{
    Program tmp = (Program) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Prog5!\n");
        exit(1);
    }
    tmp->kind = is_Prog5;
    tmp->u.prog5_.listdefinition_ = p1;
    return tmp;
}
/********************   Prog6    ********************/
Program make_Prog6(Operation p1)
{
    Program tmp = (Program) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Prog6!\n");
        exit(1);
    }
    tmp->kind = is_Prog6;
    tmp->u.prog6_.operation_ = p1;
    return tmp;
}
/********************   Prog7    ********************/
Program make_Prog7(Operation p1)
{
    Program tmp = (Program) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Prog7!\n");
        exit(1);
    }
    tmp->kind = is_Prog7;
    tmp->u.prog7_.operation_ = p1;
    return tmp;
}
/********************   Prog8    ********************/
Program make_Prog8(ListPreprocessor p1)
{
    Program tmp = (Program) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Prog8!\n");
        exit(1);
    }
    tmp->kind = is_Prog8;
    tmp->u.prog8_.listpreprocessor_ = p1;
    return tmp;
}/********************   Name    ********************/
Identifier make_Name(LIdent p1)
{
    Identifier tmp = (Identifier) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Name!\n");
        exit(1);
    }
    tmp->kind = is_Name;
    tmp->u.name_.lident_ = p1;
    return tmp;
}
/********************   QualName    ********************/
Identifier make_QualName(UIdent p1, Identifier p2)
{
    Identifier tmp = (Identifier) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating QualName!\n");
        exit(1);
    }
    tmp->kind = is_QualName;
    tmp->u.qualname_.uident_ = p1;
    tmp->u.qualname_.identifier_ = p2;
    return tmp;
}/********************   Import    ********************/
Preprocessor make_Import(String p1)
{
    Preprocessor tmp = (Preprocessor) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Import!\n");
        exit(1);
    }
    tmp->kind = is_Import;
    tmp->u.import_.string_ = p1;
    return tmp;
}
/********************   ImportAs    ********************/
Preprocessor make_ImportAs(String p1, UIdent p2)
{
    Preprocessor tmp = (Preprocessor) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ImportAs!\n");
        exit(1);
    }
    tmp->kind = is_ImportAs;
    tmp->u.importas_.string_ = p1;
    tmp->u.importas_.uident_ = p2;
    return tmp;
}
/********************   Include    ********************/
Preprocessor make_Include(String p1, UIdent p2)
{
    Preprocessor tmp = (Preprocessor) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Include!\n");
        exit(1);
    }
    tmp->kind = is_Include;
    tmp->u.include_.string_ = p1;
    tmp->u.include_.uident_ = p2;
    return tmp;
}
/********************   Define    ********************/
Preprocessor make_Define(UIdent p1)
{
    Preprocessor tmp = (Preprocessor) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Define!\n");
        exit(1);
    }
    tmp->kind = is_Define;
    tmp->u.define_.uident_ = p1;
    return tmp;
}
/********************   IF    ********************/
Preprocessor make_IF(UIdent p1, Preprocessor p2)
{
    Preprocessor tmp = (Preprocessor) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating IF!\n");
        exit(1);
    }
    tmp->kind = is_IF;
    tmp->u.if_.uident_ = p1;
    tmp->u.if_.preprocessor_ = p2;
    return tmp;
}
/********************   ELSE    ********************/
Preprocessor make_ELSE(UIdent p1, Preprocessor p2, Preprocessor p3)
{
    Preprocessor tmp = (Preprocessor) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ELSE!\n");
        exit(1);
    }
    tmp->kind = is_ELSE;
    tmp->u.else_.uident_ = p1;
    tmp->u.else_.preprocessor_1 = p2;
    tmp->u.else_.preprocessor_2 = p3;
    return tmp;
}
/********************   Error    ********************/
Preprocessor make_Error(String p1)
{
    Preprocessor tmp = (Preprocessor) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Error!\n");
        exit(1);
    }
    tmp->kind = is_Error;
    tmp->u.error_.string_ = p1;
    return tmp;
}
/********************   Warning    ********************/
Preprocessor make_Warning(String p1)
{
    Preprocessor tmp = (Preprocessor) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Warning!\n");
        exit(1);
    }
    tmp->kind = is_Warning;
    tmp->u.warning_.string_ = p1;
    return tmp;
}
/********************   Info    ********************/
Preprocessor make_Info(String p1)
{
    Preprocessor tmp = (Preprocessor) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Info!\n");
        exit(1);
    }
    tmp->kind = is_Info;
    tmp->u.info_.string_ = p1;
    return tmp;
}
/********************   FaultInt    ********************/
Preprocessor make_FaultInt(Integer p1)
{
    Preprocessor tmp = (Preprocessor) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating FaultInt!\n");
        exit(1);
    }
    tmp->kind = is_FaultInt;
    tmp->u.faultint_.integer_ = p1;
    return tmp;
}
/********************   FaultId    ********************/
Preprocessor make_FaultId(UIdent p1)
{
    Preprocessor tmp = (Preprocessor) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating FaultId!\n");
        exit(1);
    }
    tmp->kind = is_FaultId;
    tmp->u.faultid_.uident_ = p1;
    return tmp;
}/********************   Def    ********************/
Definition make_Def(LIdent p1, Operation p2)
{
    Definition tmp = (Definition) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Def!\n");
        exit(1);
    }
    tmp->kind = is_Def;
    tmp->u.def_.lident_ = p1;
    tmp->u.def_.operation_ = p2;
    return tmp;
}
/********************   Extern    ********************/
Definition make_Extern(Identifier p1, ListFFI_Type_Signature p2, FFI_Type_Signature p3)
{
    Definition tmp = (Definition) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Extern!\n");
        exit(1);
    }
    tmp->kind = is_Extern;
    tmp->u.extern_.identifier_ = p1;
    tmp->u.extern_.listffi_type_signature_ = p2;
    tmp->u.extern_.ffi_type_signature_ = p3;
    return tmp;
}
/********************   Structure    ********************/
Definition make_Structure(UIdent p1, ListRCL_Structure_Field p2)
{
    Definition tmp = (Definition) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Structure!\n");
        exit(1);
    }
    tmp->kind = is_Structure;
    tmp->u.structure_.uident_ = p1;
    tmp->u.structure_.listrcl_structure_field_ = p2;
    return tmp;
}/********************   FreeField    ********************/
RCL_Structure_Field make_FreeField(LIdent p1)
{
    RCL_Structure_Field tmp = (RCL_Structure_Field) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating FreeField!\n");
        exit(1);
    }
    tmp->kind = is_FreeField;
    tmp->u.freefield_.lident_ = p1;
    tmp->u.freefield_.hash_code = hash_djb2(p1);
    return tmp;
}
/********************   EnumField    ********************/
RCL_Structure_Field make_EnumField(LIdent p1)
{
    RCL_Structure_Field tmp = (RCL_Structure_Field) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EnumField!\n");
        exit(1);
    }
    tmp->kind = is_EnumField;
    tmp->u.enumfield_.lident_ = p1;
    tmp->u.enumfield_.hash_code = hash_djb2(p1);
    return tmp;
}
/********************   SpecField    ********************/
RCL_Structure_Field make_SpecField(LIdent p1, Identifier p2)
{
    RCL_Structure_Field tmp = (RCL_Structure_Field) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating SpecField!\n");
        exit(1);
    }
    tmp->kind = is_SpecField;
    tmp->u.specfield_.lident_ = p1;
    tmp->u.specfield_.hash_code = hash_djb2(p1);
    tmp->u.specfield_.identifier_ = p2;
    return tmp;
}/********************   TPrimitive    ********************/
FFI_Type_Signature make_TPrimitive(FFI_Type_SignatureT p1)
{
    FFI_Type_Signature tmp = (FFI_Type_Signature) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TPrimitive!\n");
        exit(1);
    }
    tmp->kind = is_TPrimitive;
    tmp->u.tprimitive_.ffi_type_signaturet_ = p1;
    return tmp;
}
/********************   TStruct    ********************/
FFI_Type_Signature make_TStruct(ListFFI_Type_Signature p1)
{
    FFI_Type_Signature tmp = (FFI_Type_Signature) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TStruct!\n");
        exit(1);
    }
    tmp->kind = is_TStruct;
    tmp->u.tstruct_.listffi_type_signature_ = p1;
    return tmp;
}
/********************   TSSelf    ********************/
FFI_Type_Signature make_TSSelf()
{
    FFI_Type_Signature tmp = (FFI_Type_Signature) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TSSelf!\n");
        exit(1);
    }
    tmp->kind = is_TSSelf;
    return tmp;
}
/********************   TPtr    ********************/
FFI_Type_Signature make_TPtr(FFI_Type_Signature p1, ListPtr p2)
{
    FFI_Type_Signature tmp = (FFI_Type_Signature) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TPtr!\n");
        exit(1);
    }
    tmp->kind = is_TPtr;
    tmp->u.tptr_.ffi_type_signature_ = p1;
    tmp->u.tptr_.listptr_ = p2;
    return tmp;
}/********************   Point    ********************/
Ptr make_Point()
{
    Ptr tmp = (Ptr) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Point!\n");
        exit(1);
    }
    tmp->kind = is_Point;
    return tmp;
}/********************   TVoid    ********************/
FFI_Type_SignatureT make_TVoid()
{
    FFI_Type_SignatureT tmp = (FFI_Type_SignatureT) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TVoid!\n");
        exit(1);
    }
    tmp->kind = is_TVoid;
    return tmp;
}
/********************   TUint8    ********************/
FFI_Type_SignatureT make_TUint8()
{
    FFI_Type_SignatureT tmp = (FFI_Type_SignatureT) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TUint8!\n");
        exit(1);
    }
    tmp->kind = is_TUint8;
    return tmp;
}
/********************   TSint8    ********************/
FFI_Type_SignatureT make_TSint8()
{
    FFI_Type_SignatureT tmp = (FFI_Type_SignatureT) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TSint8!\n");
        exit(1);
    }
    tmp->kind = is_TSint8;
    return tmp;
}
/********************   TUint16    ********************/
FFI_Type_SignatureT make_TUint16()
{
    FFI_Type_SignatureT tmp = (FFI_Type_SignatureT) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TUint16!\n");
        exit(1);
    }
    tmp->kind = is_TUint16;
    return tmp;
}
/********************   TSint16    ********************/
FFI_Type_SignatureT make_TSint16()
{
    FFI_Type_SignatureT tmp = (FFI_Type_SignatureT) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TSint16!\n");
        exit(1);
    }
    tmp->kind = is_TSint16;
    return tmp;
}
/********************   TUint32    ********************/
FFI_Type_SignatureT make_TUint32()
{
    FFI_Type_SignatureT tmp = (FFI_Type_SignatureT) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TUint32!\n");
        exit(1);
    }
    tmp->kind = is_TUint32;
    return tmp;
}
/********************   TSint32    ********************/
FFI_Type_SignatureT make_TSint32()
{
    FFI_Type_SignatureT tmp = (FFI_Type_SignatureT) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TSint32!\n");
        exit(1);
    }
    tmp->kind = is_TSint32;
    return tmp;
}
/********************   TUint64    ********************/
FFI_Type_SignatureT make_TUint64()
{
    FFI_Type_SignatureT tmp = (FFI_Type_SignatureT) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TUint64!\n");
        exit(1);
    }
    tmp->kind = is_TUint64;
    return tmp;
}
/********************   TSint64    ********************/
FFI_Type_SignatureT make_TSint64()
{
    FFI_Type_SignatureT tmp = (FFI_Type_SignatureT) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TSint64!\n");
        exit(1);
    }
    tmp->kind = is_TSint64;
    return tmp;
}
/********************   TFloat    ********************/
FFI_Type_SignatureT make_TFloat()
{
    FFI_Type_SignatureT tmp = (FFI_Type_SignatureT) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TFloat!\n");
        exit(1);
    }
    tmp->kind = is_TFloat;
    return tmp;
}
/********************   TLongDouble    ********************/
FFI_Type_SignatureT make_TLongDouble()
{
    FFI_Type_SignatureT tmp = (FFI_Type_SignatureT) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TLongDouble!\n");
        exit(1);
    }
    tmp->kind = is_TLongDouble;
    return tmp;
}
/********************   TDouble    ********************/
FFI_Type_SignatureT make_TDouble()
{
    FFI_Type_SignatureT tmp = (FFI_Type_SignatureT) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TDouble!\n");
        exit(1);
    }
    tmp->kind = is_TDouble;
    return tmp;
}
/********************   TUchar    ********************/
FFI_Type_SignatureT make_TUchar()
{
    FFI_Type_SignatureT tmp = (FFI_Type_SignatureT) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TUchar!\n");
        exit(1);
    }
    tmp->kind = is_TUchar;
    return tmp;
}
/********************   TSchar    ********************/
FFI_Type_SignatureT make_TSchar()
{
    FFI_Type_SignatureT tmp = (FFI_Type_SignatureT) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TSchar!\n");
        exit(1);
    }
    tmp->kind = is_TSchar;
    return tmp;
}
/********************   TUshort    ********************/
FFI_Type_SignatureT make_TUshort()
{
    FFI_Type_SignatureT tmp = (FFI_Type_SignatureT) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TUshort!\n");
        exit(1);
    }
    tmp->kind = is_TUshort;
    return tmp;
}
/********************   TSshort    ********************/
FFI_Type_SignatureT make_TSshort()
{
    FFI_Type_SignatureT tmp = (FFI_Type_SignatureT) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TSshort!\n");
        exit(1);
    }
    tmp->kind = is_TSshort;
    return tmp;
}
/********************   TUint    ********************/
FFI_Type_SignatureT make_TUint()
{
    FFI_Type_SignatureT tmp = (FFI_Type_SignatureT) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TUint!\n");
        exit(1);
    }
    tmp->kind = is_TUint;
    return tmp;
}
/********************   TSint    ********************/
FFI_Type_SignatureT make_TSint()
{
    FFI_Type_SignatureT tmp = (FFI_Type_SignatureT) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TSint!\n");
        exit(1);
    }
    tmp->kind = is_TSint;
    return tmp;
}
/********************   Tint    ********************/
FFI_Type_SignatureT make_Tint()
{
    FFI_Type_SignatureT tmp = (FFI_Type_SignatureT) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Tint!\n");
        exit(1);
    }
    tmp->kind = is_Tint;
    return tmp;
}
/********************   TUlong    ********************/
FFI_Type_SignatureT make_TUlong()
{
    FFI_Type_SignatureT tmp = (FFI_Type_SignatureT) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TUlong!\n");
        exit(1);
    }
    tmp->kind = is_TUlong;
    return tmp;
}
/********************   TSlong    ********************/
FFI_Type_SignatureT make_TSlong()
{
    FFI_Type_SignatureT tmp = (FFI_Type_SignatureT) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TSlong!\n");
        exit(1);
    }
    tmp->kind = is_TSlong;
    return tmp;
}
/********************   TAny    ********************/
FFI_Type_SignatureT make_TAny()
{
    FFI_Type_SignatureT tmp = (FFI_Type_SignatureT) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TAny!\n");
        exit(1);
    }
    tmp->kind = is_TAny;
    return tmp;
}/********************   Concatenation    ********************/
Operation make_Concatenation(ListOperation p1)
{
    Operation tmp = (Operation) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Concatenation!\n");
        exit(1);
    }
    tmp->kind = is_Concatenation;
    tmp->u.concatenation_.listoperation_ = p1;
    return tmp;
}
/********************   RepeatOperation    ********************/
Operation make_RepeatOperation(Integer p1, Operation p2)
{
    Operation tmp = (Operation) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating RepeatOperation!\n");
        exit(1);
    }
    tmp->kind = is_RepeatOperation;
    tmp->u.repeatoperation_.integer_ = p1;
    tmp->u.repeatoperation_.operation_ = p2;
    return tmp;
}
/********************   ParallelConcat    ********************/
Operation make_ParallelConcat(Operation p1, Operation p2)
{
    Operation tmp = (Operation) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ParallelConcat!\n");
        exit(1);
    }
    tmp->kind = is_ParallelConcat;
    tmp->u.parallelconcat_.operation_1 = p1;
    tmp->u.parallelconcat_.operation_2 = p2;
    return tmp;
}
/********************   Lambda    ********************/
Operation make_Lambda(LIdent p1)
{
    Operation tmp = (Operation) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Lambda!\n");
        exit(1);
    }
    tmp->kind = is_Lambda;
    tmp->u.lambda_.lident_ = p1;
    return tmp;
}
/********************   EndLambdaScope    ********************/
Operation make_EndLambdaScope(LIdent p1)
{
    Operation tmp = (Operation) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EndLambdaScope!\n");
        exit(1);
    }
    tmp->kind = is_EndLambdaScope;
    tmp->u.endlambdascope_.lident_ = p1;
    return tmp;
}
/********************   Quote    ********************/
Operation make_Quote(Operation p1)
{
    Operation tmp = (Operation) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Quote!\n");
        exit(1);
    }
    tmp->kind = is_Quote;
    tmp->u.quote_.operation_ = p1;
    return tmp;
}
/********************   List    ********************/
Operation make_List(ListOperation p1)
{
    Operation tmp = (Operation) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating List!\n");
        exit(1);
    }
    tmp->kind = is_List;
    tmp->u.list_.listoperation_ = p1;
    return tmp;
}
/********************   Var    ********************/
Operation make_Var(Identifier p1)
{
    Operation tmp = (Operation) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Var!\n");
        exit(1);
    }
    tmp->kind = is_Var;
    tmp->u.var_.identifier_ = p1;
    return tmp;
}
/********************   Lit    ********************/
Operation make_Lit(Data p1)
{
    Operation tmp = (Operation) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Lit!\n");
        exit(1);
    }
    tmp->kind = is_Lit;
    tmp->u.lit_.data_ = p1;
    return tmp;
}
/********************   BasicLiteralOp    ********************/
Operation make_BasicLiteralOp(LiteralOperation p1)
{
    Operation tmp = (Operation) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating BasicLiteralOp!\n");
        exit(1);
    }
    tmp->kind = is_BasicLiteralOp;
    tmp->u.basicliteralop_.literaloperation_ = p1;
    return tmp;
}
/********************   Field    ********************/
Operation make_Field(RCL_Structure_Field p1)
{
    Operation tmp = (Operation) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Field!\n");
        exit(1);
    }
    tmp->kind = is_Field;
    tmp->u.field_.rcl_structure_field_ = p1;
    return tmp;
}/********************   Add    ********************/
LiteralOperation make_Add()
{
    LiteralOperation tmp = (LiteralOperation) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Add!\n");
        exit(1);
    }
    tmp->kind = is_Add;
    return tmp;
}
/********************   Sub    ********************/
LiteralOperation make_Sub()
{
    LiteralOperation tmp = (LiteralOperation) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Sub!\n");
        exit(1);
    }
    tmp->kind = is_Sub;
    return tmp;
}
/********************   Pow    ********************/
LiteralOperation make_Pow()
{
    LiteralOperation tmp = (LiteralOperation) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Pow!\n");
        exit(1);
    }
    tmp->kind = is_Pow;
    return tmp;
}
/********************   Mul    ********************/
LiteralOperation make_Mul()
{
    LiteralOperation tmp = (LiteralOperation) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Mul!\n");
        exit(1);
    }
    tmp->kind = is_Mul;
    return tmp;
}
/********************   Div    ********************/
LiteralOperation make_Div()
{
    LiteralOperation tmp = (LiteralOperation) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Div!\n");
        exit(1);
    }
    tmp->kind = is_Div;
    return tmp;
}
/********************   Mod    ********************/
LiteralOperation make_Mod()
{
    LiteralOperation tmp = (LiteralOperation) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Mod!\n");
        exit(1);
    }
    tmp->kind = is_Mod;
    return tmp;
}
/********************   Inc    ********************/
LiteralOperation make_Inc()
{
    LiteralOperation tmp = (LiteralOperation) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Inc!\n");
        exit(1);
    }
    tmp->kind = is_Inc;
    return tmp;
}
/********************   Dec    ********************/
LiteralOperation make_Dec()
{
    LiteralOperation tmp = (LiteralOperation) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Dec!\n");
        exit(1);
    }
    tmp->kind = is_Dec;
    return tmp;
}
/********************   BAnd    ********************/
LiteralOperation make_BAnd()
{
    LiteralOperation tmp = (LiteralOperation) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating BAnd!\n");
        exit(1);
    }
    tmp->kind = is_BAnd;
    return tmp;
}
/********************   BOr    ********************/
LiteralOperation make_BOr()
{
    LiteralOperation tmp = (LiteralOperation) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating BOr!\n");
        exit(1);
    }
    tmp->kind = is_BOr;
    return tmp;
}
/********************   BXor    ********************/
LiteralOperation make_BXor()
{
    LiteralOperation tmp = (LiteralOperation) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating BXor!\n");
        exit(1);
    }
    tmp->kind = is_BXor;
    return tmp;
}
/********************   BLeft    ********************/
LiteralOperation make_BLeft()
{
    LiteralOperation tmp = (LiteralOperation) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating BLeft!\n");
        exit(1);
    }
    tmp->kind = is_BLeft;
    return tmp;
}
/********************   BRight    ********************/
LiteralOperation make_BRight()
{
    LiteralOperation tmp = (LiteralOperation) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating BRight!\n");
        exit(1);
    }
    tmp->kind = is_BRight;
    return tmp;
}/********************   Int    ********************/
Data make_Int(Integer p1)
{
    Data tmp = (Data) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Int!\n");
        exit(1);
    }
    tmp->kind = is_Int;
    tmp->u.int_.integer_ = p1;
    return tmp;
}
/********************   Flt    ********************/
Data make_Flt(Double p1)
{
    Data tmp = (Data) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Flt!\n");
        exit(1);
    }
    tmp->kind = is_Flt;
    tmp->u.flt_.double_ = p1;
    return tmp;
}
/********************   Chr    ********************/
Data make_Chr(Char p1)
{
    Data tmp = (Data) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Chr!\n");
        exit(1);
    }
    tmp->kind = is_Chr;
    tmp->u.chr_.char_ = p1;
    return tmp;
}
/********************   Str    ********************/
Data make_Str(String p1)
{
    Data tmp = (Data) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Str!\n");
        exit(1);
    }
    tmp->kind = is_Str;
    tmp->u.str_.string_ = p1;
    return tmp;
}/********************   ListOperation    ********************/
ListOperation make_ListOperation(Operation p1, ListOperation p2)
{
    ListOperation tmp = (ListOperation) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListOperation!\n");
        exit(1);
    }
    tmp->operation_ = p1;
    tmp->listoperation_ = p2;
    return tmp;
}/********************   ListFFI_Type_Signature    ********************/
ListFFI_Type_Signature make_ListFFI_Type_Signature(FFI_Type_Signature p1, ListFFI_Type_Signature p2)
{
    ListFFI_Type_Signature tmp = (ListFFI_Type_Signature) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListFFI_Type_Signature!\n");
        exit(1);
    }
    tmp->ffi_type_signature_ = p1;
    tmp->listffi_type_signature_ = p2;
    return tmp;
}/********************   ListPtr    ********************/
ListPtr make_ListPtr(Ptr p1, ListPtr p2)
{
    ListPtr tmp = (ListPtr) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListPtr!\n");
        exit(1);
    }
    tmp->ptr_ = p1;
    tmp->listptr_ = p2;
    return tmp;
}/********************   ListDefinition    ********************/
ListDefinition make_ListDefinition(Definition p1, ListDefinition p2)
{
    ListDefinition tmp = (ListDefinition) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListDefinition!\n");
        exit(1);
    }
    tmp->definition_ = p1;
    tmp->listdefinition_ = p2;
    return tmp;
}/********************   ListPreprocessor    ********************/
ListPreprocessor make_ListPreprocessor(Preprocessor p1, ListPreprocessor p2)
{
    ListPreprocessor tmp = (ListPreprocessor) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListPreprocessor!\n");
        exit(1);
    }
    tmp->preprocessor_ = p1;
    tmp->listpreprocessor_ = p2;
    return tmp;
}/********************   ListRCL_Structure_Field    ********************/
ListRCL_Structure_Field make_ListRCL_Structure_Field(RCL_Structure_Field p1, ListRCL_Structure_Field p2)
{
    ListRCL_Structure_Field tmp = (ListRCL_Structure_Field) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListRCL_Structure_Field!\n");
        exit(1);
    }
    tmp->rcl_structure_field_ = p1;
    tmp->listrcl_structure_field_ = p2;
    return tmp;
}
