/*
 * Copyright (c) 2019-2020 vanaur.
 *
 * This file is part of RCL
 * (see https://github.com/vanaur/The-Runtime-Core-Library).
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

#define yy_create_buffer RCL_create_buffer
#define yy_delete_buffer RCL_delete_buffer
#define yy_scan_buffer RCL_scan_buffer
#define yy_scan_string RCL_scan_string
#define yy_scan_bytes RCL_scan_bytes
#define yy_flex_debug RCL_flex_debug
#define yy_init_buffer RCL_init_buffer
#define yy_flush_buffer RCL_flush_buffer
#define yy_load_buffer_state RCL_load_buffer_state
#define yy_switch_to_buffer RCL_switch_to_buffer
#define yyin RCLin
#define yyleng RCLleng
#define yylex RCLlex
#define yyout RCLout
#define yyrestart RCLrestart
#define yytext RCLtext

#line 19 "Lexer.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 98
#define YY_END_OF_BUFFER 99
static yyconst short int yy_accept[242] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   99,   98,   95,   97,
       96,   95,    9,   77,   15,   17,   24,   27,   86,    6,
        7,   13,   20,   32,   21,    4,   23,   94,   97,   33,
       97,    5,   97,   75,   11,   16,   12,   29,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       18,   28,   19,   14,   73,   74,   73,   88,   88,   87,
       91,   89,   90,   92,   80,   79,   78,   85,   82,   83,
       81,   84,   22,   25,   26,    8,    0,    0,    0,   71,
        0,    0,   94,   10,   30,   31,   75,   76,   76,   35,

       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   72,    0,    0,    0,    0,   70,
       93,   34,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   47,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,    0,    0,
        0,    0,   76,   76,   38,   76,   76,   76,   76,   76,
       76,   76,   46,   48,   76,   50,   51,   76,   76,   76,
       59,   76,   61,   76,   76,   68,   76,    0,    0,    3,
        0,   93,   76,   76,   39,   76,   41,   42,   43,   76,

       76,   49,   76,   76,   76,   55,   56,   76,   76,   60,
       76,   76,   76,   65,   66,   76,   76,    0,    1,   36,
       37,   40,   44,   76,   52,   53,   54,   57,   76,   62,
       63,   64,   67,   76,    2,   45,   76,   69,   76,   58,
        0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   19,   24,   19,   25,   19,   26,   27,   28,
       29,   30,    1,    1,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       32,   33,   34,   35,   36,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   46,   46,   47,   48,   49,
       50,   51,   46,   52,   53,   54,   55,   56,   57,   58,
       59,   46,   60,   61,   62,   63,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[64] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    2,
        2,    2,    2,    2,    2,    1,    1,    1,    1,    1,
        2,    1,    1,    1,    1,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    1,
        1,    1,    1
    } ;

static yyconst short int yy_base[251] =
    {   0,
      318,  317,    0,    0,   61,   62,   63,   66,   64,   65,
       67,   68,   76,   77,   82,   83,  319,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  305,  303,  322,   67,   44,   77,   81,  290,  322,
      287,  322,  284,    0,  322,  322,  322,  322,   58,    0,
       67,   75,   83,   86,  263,   99,  268,  102,  261,  273,
      322,  322,  322,  322,  322,  322,  291,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  267,  267,  269,  322,
      302,  137,  146,  322,  322,  322,    0,    0,  245,    0,

      261,  247,  248,  248,  245,  243,  247,  256,  244,  100,
      245,  249,  245,  242,  240,  245,  236,  246,  242,  236,
      234,  239,  237,  229,  322,  238,  242,  233,  274,  322,
      153,    0,  231,  237,  233,  223,  231,  224,  233,  228,
      218,  220,  216,    0,  222,  227,  221,  208,  212,  210,
      204,  209,  220,  202,  206,  204,  213,  203,  206,  196,
      200,  163,  199,  200,    0,  194,  193,  190,  189,  200,
      189,  185,    0,    0,  187,    0,  101,  195,  185,  197,
        0,  183,  171,  191,  181,    0,  187,  182,  193,  322,
      178,  185,  188,  187,    0,  178,    0,    0,    0,  172,

      185,    0,  168,  169,  166,    0,    0,  127,  126,    0,
      140,  130,  127,    0,    0,   94,   96,  102,  322,    0,
        0,    0,    0,   88,    0,    0,    0,    0,   69,    0,
        0,    0,    0,   69,  322,    0,   42,    0,   52,    0,
      322,  210,  212,  214,  216,  218,  220,   89,   70,  222
    } ;

static yyconst short int yy_def[251] =
    {   0,
      242,  242,  241,    3,  243,  243,  244,  244,  245,  245,
      242,  242,  246,  246,  247,  247,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  248,  241,  241,  241,  241,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      250,  241,  241,  241,  241,  241,  248,  249,  249,  249,

      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  241,  241,  241,  241,  250,  241,
      241,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  241,  241,
      241,  241,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  241,  241,  241,
      241,  241,  249,  249,  249,  249,  249,  249,  249,  249,

      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  241,  241,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  241,  249,  249,  249,  249,  249,
        0,  241,  241,  241,  241,  241,  241,  241,  241,  241
    } ;

static yyconst short int yy_nxt[386] =
    {   0,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   38,
       38,   38,   38,   38,   38,   39,   40,   41,   42,   43,
       44,   45,   46,   47,   48,   20,   49,   50,   50,   51,
       52,   53,   50,   50,   54,   50,   55,   50,   50,   50,
       50,   50,   56,   57,   58,   59,   60,   50,   50,   61,
       62,   63,   64,   66,   66,   69,   19,   19,   69,   19,
       19,   98,   18,   67,   67,   18,   74,   74,   19,   19,
       76,   76,   85,   87,   19,   19,   79,   79,   88,   90,
       97,   89,  240,  239,   91,   70,   86,   92,   70,   93,

       93,   93,   93,   93,   93,   93,   99,  101,   77,   77,
      100,  238,   72,   72,   80,   80,  102,   73,   73,  106,
      203,  103,  204,  237,  205,  206,  104,  108,  236,  107,
       81,   81,  105,  109,  110,   82,   82,  112,  142,  113,
      119,  143,  235,  114,  234,  115,  120,  233,  121,  232,
      231,  116,  117,  144,  122,  131,  131,  131,  131,  131,
      131,  131,   92,  230,   93,   93,   93,   93,   93,   93,
       93,  131,  131,  131,  131,  131,  131,  131,  191,  229,
      228,  192,  192,  192,  192,  192,  192,  192,  227,  226,
      211,  225,  212,  162,  213,  214,  192,  192,  192,  192,

      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
       18,   18,   65,   65,   68,   68,   71,   71,   75,   75,
       78,   78,  129,  129,  224,  223,  222,  221,  220,  219,
      218,  217,  216,  215,  210,  209,  208,  207,  202,  201,
      200,  199,  198,  197,  196,  195,  194,  193,  190,  189,
      188,  187,  186,  185,  184,  183,  182,  181,  180,  179,
      178,  177,  176,  175,  174,  173,  172,  171,  170,  169,
      168,  167,  166,  165,  164,  163,  130,  161,  160,  159,
      158,  157,  156,  155,  154,  153,  152,  151,  150,  149,
      148,  147,  146,  145,  141,  140,  139,  138,  137,  136,

      135,  134,  133,  132,  130,  128,  127,  126,  125,  124,
      123,  118,  111,   96,   95,   94,   84,   83,  241,   19,
       19,   17,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241
    } ;

static yyconst short int yy_chk[386] =
    {   0,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    5,    6,    7,    9,   10,    8,   11,
       12,  249,    7,    5,    6,    8,   11,   12,   13,   14,
       13,   14,   35,   36,   15,   16,   15,   16,   36,   37,
      248,   36,  239,  237,   37,    7,   35,   38,    8,   38,

       38,   38,   38,   38,   38,   38,   49,   51,   13,   14,
       49,  234,    9,   10,   15,   16,   51,    9,   10,   53,
      177,   52,  177,  229,  177,  177,   52,   54,  224,   53,
       15,   16,   52,   54,   54,   15,   16,   56,  110,   56,
       58,  110,  218,   56,  217,   56,   58,  216,   58,  213,
      212,   56,   56,  110,   58,   92,   92,   92,   92,   92,
       92,   92,   93,  211,   93,   93,   93,   93,   93,   93,
       93,  131,  131,  131,  131,  131,  131,  131,  162,  209,
      208,  162,  162,  162,  162,  162,  162,  162,  205,  204,
      183,  203,  183,  131,  183,  183,  191,  191,  191,  191,

      191,  191,  191,  192,  192,  192,  192,  192,  192,  192,
      242,  242,  243,  243,  244,  244,  245,  245,  246,  246,
      247,  247,  250,  250,  201,  200,  196,  194,  193,  189,
      188,  187,  185,  184,  182,  180,  179,  178,  175,  172,
      171,  170,  169,  168,  167,  166,  164,  163,  161,  160,
      159,  158,  157,  156,  155,  154,  153,  152,  151,  150,
      149,  148,  147,  146,  145,  143,  142,  141,  140,  139,
      138,  137,  136,  135,  134,  133,  129,  128,  127,  126,
      124,  123,  122,  121,  120,  119,  118,  117,  116,  115,
      114,  113,  112,  111,  109,  108,  107,  106,  105,  104,

      103,  102,  101,   99,   91,   89,   88,   87,   67,   60,
       59,   57,   55,   43,   41,   39,   33,   32,   17,    2,
        1,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "RCL.l"
#define INITIAL 0
/* -*- c -*- This FLex file was machine-generated by the BNF converter */
#line 4 "RCL.l"
#define yylval RCLlval
#define YY_BUFFER_APPEND RCL_BUFFER_APPEND
#define YY_BUFFER_RESET RCL_BUFFER_RESET
#define initialize_lexer RCL_initialize_lexer
#include <string.h>
#include <VM\Core\Syntax\Parser.h>
#define YY_BUFFER_LENGTH 4096
extern int yy_mylinenumber ;
char YY_PARSED_STRING[YY_BUFFER_LENGTH];
void YY_BUFFER_APPEND(char *s)
{
  strcat(YY_PARSED_STRING, s); //Do something better here!
}
void YY_BUFFER_RESET(void)
{
  int x;
  for(x = 0; x < YY_BUFFER_LENGTH; x++)
    YY_PARSED_STRING[x] = 0;
}

#define YYINITIAL 1
#define COMMENT 2
#define CHAR 3
#define CHARESC 4
#define CHAREND 5
#define STRING 6
#define ESCAPED 7

#line 580 "Lexer.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 32 "RCL.l"


#line 734 "Lexer.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 242 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 322 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 34 "RCL.l"
return _SYMB_0;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 35 "RCL.l"
return _SYMB_1;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 36 "RCL.l"
return _SYMB_2;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 37 "RCL.l"
return _SYMB_3;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 38 "RCL.l"
return _SYMB_4;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 39 "RCL.l"
return _SYMB_5;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 40 "RCL.l"
return _SYMB_6;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 41 "RCL.l"
return _SYMB_7;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 42 "RCL.l"
return _SYMB_8;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 43 "RCL.l"
return _SYMB_9;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 44 "RCL.l"
return _SYMB_10;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 45 "RCL.l"
return _SYMB_11;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 46 "RCL.l"
return _SYMB_12;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 47 "RCL.l"
return _SYMB_13;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 48 "RCL.l"
return _SYMB_14;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 49 "RCL.l"
return _SYMB_15;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 50 "RCL.l"
return _SYMB_16;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 51 "RCL.l"
return _SYMB_17;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 52 "RCL.l"
return _SYMB_18;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 53 "RCL.l"
return _SYMB_19;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 54 "RCL.l"
return _SYMB_20;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 55 "RCL.l"
return _SYMB_21;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 56 "RCL.l"
return _SYMB_22;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 57 "RCL.l"
return _SYMB_23;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 58 "RCL.l"
return _SYMB_24;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 59 "RCL.l"
return _SYMB_25;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 60 "RCL.l"
return _SYMB_26;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 61 "RCL.l"
return _SYMB_27;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 62 "RCL.l"
return _SYMB_28;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 63 "RCL.l"
return _SYMB_29;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 64 "RCL.l"
return _SYMB_30;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 65 "RCL.l"
return _SYMB_31;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 66 "RCL.l"
return _SYMB_32;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 67 "RCL.l"
return _SYMB_33;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 68 "RCL.l"
return _SYMB_34;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 69 "RCL.l"
return _SYMB_35;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 70 "RCL.l"
return _SYMB_36;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 71 "RCL.l"
return _SYMB_37;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 72 "RCL.l"
return _SYMB_38;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 73 "RCL.l"
return _SYMB_39;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 74 "RCL.l"
return _SYMB_40;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 75 "RCL.l"
return _SYMB_41;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 76 "RCL.l"
return _SYMB_42;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 77 "RCL.l"
return _SYMB_43;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 78 "RCL.l"
return _SYMB_44;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 79 "RCL.l"
return _SYMB_45;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 80 "RCL.l"
return _SYMB_46;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 81 "RCL.l"
return _SYMB_47;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 82 "RCL.l"
return _SYMB_48;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 83 "RCL.l"
return _SYMB_49;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 84 "RCL.l"
return _SYMB_50;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 85 "RCL.l"
return _SYMB_51;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 86 "RCL.l"
return _SYMB_52;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 87 "RCL.l"
return _SYMB_53;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 88 "RCL.l"
return _SYMB_54;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 89 "RCL.l"
return _SYMB_55;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 90 "RCL.l"
return _SYMB_56;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 91 "RCL.l"
return _SYMB_57;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 92 "RCL.l"
return _SYMB_58;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 93 "RCL.l"
return _SYMB_59;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 94 "RCL.l"
return _SYMB_60;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 95 "RCL.l"
return _SYMB_61;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 96 "RCL.l"
return _SYMB_62;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 97 "RCL.l"
return _SYMB_63;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 98 "RCL.l"
return _SYMB_64;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 99 "RCL.l"
return _SYMB_65;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 100 "RCL.l"
return _SYMB_66;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 101 "RCL.l"
return _SYMB_67;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 102 "RCL.l"
return _SYMB_68;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 104 "RCL.l"
++yy_mylinenumber; // BNFC: comment "//";
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 105 "RCL.l"
BEGIN COMMENT; // BNFC: comment "/*" "*/";
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 106 "RCL.l"
BEGIN YYINITIAL;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 107 "RCL.l"
/* skip */;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 108 "RCL.l"
++yy_mylinenumber;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 110 "RCL.l"
yylval.string_ = strdup(yytext); return _SYMB_69;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 111 "RCL.l"
yylval.string_ = strdup(yytext); return _SYMB_70;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 112 "RCL.l"
BEGIN STRING;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 113 "RCL.l"
BEGIN ESCAPED;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 114 "RCL.l"
yylval.string_ = strdup(YY_PARSED_STRING); YY_BUFFER_RESET(); BEGIN YYINITIAL; return _STRING_;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 115 "RCL.l"
YY_BUFFER_APPEND(yytext);
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 116 "RCL.l"
YY_BUFFER_APPEND("\n"); BEGIN STRING;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 117 "RCL.l"
YY_BUFFER_APPEND("\""); BEGIN STRING ;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 118 "RCL.l"
YY_BUFFER_APPEND("\\"); BEGIN STRING;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 119 "RCL.l"
YY_BUFFER_APPEND("\t"); BEGIN STRING;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 120 "RCL.l"
YY_BUFFER_APPEND(yytext); BEGIN STRING;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 121 "RCL.l"
BEGIN CHAR;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 122 "RCL.l"
BEGIN CHARESC;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 123 "RCL.l"
BEGIN CHAREND; yylval.char_ = yytext[0]; return _CHAR_;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 124 "RCL.l"
BEGIN CHAREND; yylval.char_ = '\n'; return _CHAR_;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 125 "RCL.l"
BEGIN CHAREND; yylval.char_ = '\t'; return _CHAR_;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 126 "RCL.l"
BEGIN CHAREND; yylval.char_ = yytext[0]; return _CHAR_;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 127 "RCL.l"
BEGIN YYINITIAL;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 128 "RCL.l"
yylval.double_ = atof(yytext); return _DOUBLE_;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 129 "RCL.l"
yylval.int_ = atoi(yytext); return _INTEGER_;
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 130 "RCL.l"
++yy_mylinenumber ;
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 131 "RCL.l"
/* ignore white space. */;
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 132 "RCL.l"
return _ERROR_;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 133 "RCL.l"
ECHO;
	YY_BREAK
#line 1307 "Lexer.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(YYINITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(CHAR):
case YY_STATE_EOF(CHARESC):
case YY_STATE_EOF(CHAREND):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(ESCAPED):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 242 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 242 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 241);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 133 "RCL.l"

void initialize_lexer(FILE *inp) { yyrestart(inp); BEGIN YYINITIAL; }
